config/routes.rb
Rails.application.routes.draw do
  # Routes for the Follow request resource:

  # CREATE
  post("/insert_follow_request", { :controller => "follow_requests", :action => "create" })
          
  # READ
  get("/follow_requests", { :controller => "follow_requests", :action => "index" })
  
  get("/follow_requests/:path_id", { :controller => "follow_requests", :action => "show" })
  
  # UPDATE
  
  post("/modify_follow_request/:path_id", { :controller => "follow_requests", :action => "update" })
  
  # DELETE
  get("/delete_follow_request/:path_id", { :controller => "follow_requests", :action => "destroy" })

  #------------------------------

  # Routes for the Post resource:

  # CREATE
  post("/insert_post", { :controller => "posts", :action => "create" })
          
  # READ
  get("/posts", { :controller => "posts", :action => "index" })
  
  get("/posts/:path_id", { :controller => "posts", :action => "show" })

  # Routes for Comments
post "/insert_comment", { controller: "comments", action: "create" }

# Routes for Likes
post "/insert_like", { controller: "likes", action: "create" }



  resources :posts do
    resources :comments, only: [:index, :create]
  end
  
  
  # UPDATE
  
  post("/modify_post/:path_id", { :controller => "posts", :action => "update" })
  
  # DELETE
  get("/delete_post/:path_id", { :controller => "posts", :action => "destroy" })

  #------------------------------

  # Routes for the Like resource:

  # CREATE
  post("/insert_like", { :controller => "likes", :action => "create" })
          
  # READ
  get("/likes", { :controller => "likes", :action => "index" })
  
  get("/likes/:path_id", { :controller => "likes", :action => "show" })
  
  # UPDATE
  
  post("/modify_like/:path_id", { :controller => "likes", :action => "update" })
  
  # DELETE
  get("/delete_like/:path_id", { :controller => "likes", :action => "destroy" })

  #------------------------------

  # Routes for the Comment resource:


  # CREATE
  post("/insert_comment", { :controller => "comments", :action => "create" })
          
  # READ
  get("/comments", { :controller => "comments", :action => "index" })
  
  get("/comments/:path_id", { :controller => "comments", :action => "show" })
  
  # UPDATE
  
  post("/modify_comment/:path_id", { :controller => "comments", :action => "update" })
  
  # DELETE
  get("/delete_comment/:path_id", { :controller => "comments", :action => "destroy" })

  #------------------------------

  # Routes for the Job application resource:

  # CREATE

  post("/insert_job_application", { :controller => "job_applications", :action => "create" })
          
  # READ
  get("/job_applications", { :controller => "job_applications", :action => "index" })
  
  get("/job_applications/:path_id", { :controller => "job_applications", :action => "show" })
  
  # UPDATE
  
  post("/modify_job_application/:path_id", { :controller => "job_applications", :action => "update" })
  
  # DELETE
  get("/delete_job_application/:path_id", { :controller => "job_applications", :action => "destroy" })

  #------------------------------

  # Routes for the Job posting resource:

  # CREATE

  post("/insert_job_posting", { :controller => "job_postings", :action => "create" })
          
  # READ
  get("/job_postings", { :controller => "job_postings", :action => "index" })
  
  resources :job_postings, only: [:index, :show]

  get("/job_postings/:path_id", { :controller => "job_postings", :action => "show" })
  

  # UPDATE
  
  post("/modify_job_posting/:path_id", { :controller => "job_postings", :action => "update" })
  
  # DELETE
  get("/delete_job_posting/:path_id", { :controller => "job_postings", :action => "destroy" })

  resources :job_postings do
    resources :job_applications, only: [:new, :create, :index]

  end
  

  #------------------------------

  devise_for :users

  get "/alumni_directory", { :controller => "users", :action => "directory" }
  get "/users/:user_id/posts", { :controller => "posts", :action => "user_posts" }
  root to: "pages#home"

  get "/profile/edit", to: "users#edit", as: "edit_profile"
  patch "/profile", to: "users#update", as: "update_profile"



  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"

  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                        :bigint           not null, primary key
#  admin                     :boolean
#  alumn                     :boolean
#  city_of_residence         :string
#  company                   :string
#  country_of_residence      :string
#  dob                       :date
#  email                     :string           default(""), not null
#  encrypted_password        :string           default(""), not null
#  industry_of_occupation    :string
#  name                      :string
#  professor                 :boolean
#  profile_picture           :string
#  remember_created_at       :datetime
#  reset_password_sent_at    :datetime
#  reset_password_token      :string
#  sent_follow_request_count :integer
#  student                   :boolean
#  whatsapp                  :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Active Storage for profile picture
  has_one_attached :profile_picture

  # Associations
  has_many :posts, class_name: "Post", foreign_key: "user_id", dependent: :destroy
  has_many :job_applications, class_name: "JobApplication", foreign_key: "user_id", dependent: :destroy
  has_many :job_postings, class_name: "JobPosting", foreign_key: "user_id", dependent: :destroy
  has_many :likes, class_name: "Like", foreign_key: "user_id", dependent: :destroy
  has_many :comments, class_name: "Comment", foreign_key: "user_id", dependent: :destroy
  has_many :sent_follow_request, class_name: "FollowRequest", foreign_key: "sender_id", dependent: :destroy
  has_many :received_follow_request, class_name: "FollowRequest", foreign_key: "recipient_id", dependent: :destroy

  # Validations
  validate :profile_picture_format

  private

  def profile_picture_format
    return unless profile_picture.attached?

    unless profile_picture.content_type.in?(%w[image/jpeg])
      errors.add(:profile_picture, "must be a JPEG file")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def directory
    @users = User.all

    # Filter by admin
    @users = @users.where(admin: true) if params[:admin] == "1"

    # Filter by alumn
    @users = @users.where(alumn: true) if params[:alumn] == "1"

    # Filter by student
    @users = @users.where(student: true) if params[:student] == "1"

    # Filter by professor
    @users = @users.where(professor: true) if params[:professor] == "1"

    # Filter by other fields
    @users = @users.where(country_of_residence: params[:country_of_residence]) if params[:country_of_residence].present?
    @users = @users.where(company: params[:company]) if params[:company].present?
    @users = @users.where(industry_of_occupation: params[:industry_of_occupation]) if params[:industry_of_occupation].present?

    # Filter by date of birth range
    if params[:dob].present?
      begin
        dob_date = Date.parse(params[:dob])
        @users = @users.where(dob: dob_date)
      rescue ArgumentError
        flash.now[:alert] = "Invalid date format."
      end
    end

    render :directory
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to edit_profile_path, notice: "Profile updated successfully."
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :admin,
      :alumn,
      :dob,
      :profile_picture,
      :country_of_residence,
      :industry_of_occupation,
      :company,
      :city_of_residence,
      :student,
      :professor,
      :whatsapp
    )
  end
end

app/views/users/directory.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Alumni Directory</h1>

  <!-- Filter Form -->
  <%= form_with(url: alumni_directory_path, method: :get, local: true, class: "mb-4") do %>
    <fieldset class="border p-4 rounded shadow-sm">
      <legend class="w-auto px-2 text-primary">Filter Users</legend>
      
      <div class="row mb-3">
        <div class="col-md-3">
          <label for="admin">Admin:</label>
          <input type="checkbox" name="admin" id="admin" value="1" <%= "checked" if params[:admin] == "1" %>>
        </div>
        <div class="col-md-3">
          <label for="alumn">Alumn:</label>
          <input type="checkbox" name="alumn" id="alumn" value="1" <%= "checked" if params[:alumn] == "1" %>>
        </div>
        <div class="col-md-3">
          <label for="student">Student:</label>
          <input type="checkbox" name="student" id="student" value="1" <%= "checked" if params[:student] == "1" %>>
        </div>
        <div class="col-md-3">
          <label for="professor">Professor:</label>
          <input type="checkbox" name="professor" id="professor" value="1" <%= "checked" if params[:professor] == "1" %>>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-4">
          <label for="country_of_residence">Country of Residence:</label>
          <select name="country_of_residence" id="country_of_residence" class="form-control">
            <option value="">All Countries</option>
            <% User.distinct.pluck(:country_of_residence).compact.each do |country| %>
              <option value="<%= country %>" <%= "selected" if params[:country_of_residence] == country %>>
                <%= country %>
              </option>
            <% end %>
          </select>
        </div>
        <div class="col-md-4">
          <label for="company">Company:</label>
          <input type="text" name="company" id="company" class="form-control" value="<%= params[:company] %>">
        </div>
        <div class="col-md-4">
          <label for="industry_of_occupation">Industry of Occupation:</label>
          <select name="industry_of_occupation" id="industry_of_occupation" class="form-control">
            <option value="">All Industries</option>
            <% User.distinct.pluck(:industry_of_occupation).compact.each do |industry| %>
              <option value="<%= industry %>" <%= "selected" if params[:industry_of_occupation] == industry %>>
                <%= industry %>
              </option>
            <% end %>
          </select>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-4">
          <label for="dob">Date of Birth:</label>
          <input type="date" name="dob" id="dob" class="form-control" value="<%= params[:dob] %>">
        </div>
      </div>

      <div>
        <button type="submit" class="btn btn-primary">Search</button>
      </div>
    </fieldset>
  <% end %>

  <hr>

  <!-- Results Table -->
  <div>
    <table class="table table-striped table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Profile Picture</th>
          <th>Role</th>
          <th>Country</th>
          <th>City</th>
          <th>Company</th>
          <th>Industry</th>
          <th>Date of Birth</th>
        </tr>
      </thead>
      <tbody>
        <% if @users.present? %>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name || "N/A" %></td>
              <td>
                <% if user.profile_picture.present? %>
                  <%= image_tag user.profile_picture, alt: "Profile Picture", class: "img-thumbnail", width: 50, height: 50 %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td>
                <% if user.admin %>
                  Admin
                <% elsif user.alumn %>
                  Alumn
                <% elsif user.student %>
                  Student
                <% elsif user.professor %>
                  Professor
                <% else %>
                  N/A
                <% end %>
              </td>
              <td><%= user.country_of_residence || "N/A" %></td>
              <td><%= user.city_of_residence || "N/A" %></td>
              <td><%= user.company || "N/A" %></td>
              <td><%= user.industry_of_occupation || "N/A" %></td>
              <td><%= user.dob || "N/A" %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="8" class="text-center">No users found.</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= form_with model: @user, url: update_profile_path, method: :patch, local: true, class: "form" do |f| %>
  <div class="form-group">
    <label>User ID:</label>
    <span id="user_id"><%= @user.id %></span>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email (cannot be changed)" %>
    <%= f.text_field :email, disabled: true, class: "form-control" %>
  </div>

    <div class="form-group">
    <%= f.label :whatsapp, "Whatsapp (phone number)" %>
    <%= f.text_field :whatsapp, class: "form-control" %>
  </div>

<div class="form-group form-check">
  <%= f.check_box :admin, id: "admin", class: "form-check-input" %>
  <%= f.label :admin, "Admin", for: "admin", class: "form-check-label" %>
</div>

<div class="form-group form-check">
  <%= f.check_box :student, id: "student", class: "form-check-input" %>
  <%= f.label :student, "Student", for: "student", class: "form-check-label" %>
</div>

<div class="form-group form-check">
  <%= f.check_box :alumn, id: "alumn", class: "form-check-input" %>
  <%= f.label :alumn, "Alumn", for: "alumn", class: "form-check-label" %>
</div>

  <div class="form-group">
    <%= f.label :dob, "Date of Birth" %>
    <%= f.date_field :dob, class: "form-control" %>
  </div>

<div class="form-group">
  <%= f.label :profile_picture, "Profile Picture (JPG only)" %>
  <%= f.file_field :profile_picture, accept: "image/jpeg", class: "form-control" %>
</div>


  <div class="form-group">
    <%= f.label :country_of_residence, "Country of Residence" %>
    <%= f.text_field :country_of_residence, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city_of_residence, "City of Residence" %>
    <%= f.text_field :city_of_residence, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :industry_of_occupation, "Industry of Occupation" %>
    <%= f.text_field :industry_of_occupation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company, "Company" %>
    <%= f.text_field :company, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update Profile", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="mt-3">
  <h2>Details for <%= @user.email %></h2>
  <%= link_to "Back to Home", root_path, class: "btn btn-secondary" %>
</div>

app/views/users/show.html.erb
<h1>Edit Your Profile</h1>

<%= form_with model: @user, url: update_profile_path, method: :patch, local: true do |f| %>
  <div>
    <%= f.label :email, "Email (cannot be changed)" %><br />
    <%= f.text_field :email, disabled: true %>
  </div>

    <div>
    <%= f.label :whatsapp, "Whatsapp Phone Number" %><br />
    <%= f.text_field :whatsapp %>
  </div>

  <div>
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>

  <div>
    <%= f.label :alumn %><br />
    <%= f.check_box :alumn %>
  </div>

  <div>
    <%= f.label :dob, "Date of Birth" %><br />
    <%= f.date_field :dob %>
  </div>

  <div>
    <%= f.label :profile_picture, "Profile Picture (URL)" %><br />
    <%= f.text_field :profile_picture %>
  </div>

  <div>
    <%= f.label :country_of_residence %><br />
    <%= f.text_field :country_of_residence %>
  </div>

  <div>
    <%= f.label :city_of_residence %><br />
    <%= f.text_field :city_of_residence %>
  </div>

  <div>
    <%= f.label :industry_of_occupation, "Industry of Occupation" %><br />
    <%= f.text_field :industry_of_occupation %>
  </div>

  <div>
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>

  <div>
    <%= f.label :student %><br />
    <%= f.check_box :student %>
  </div>

  <div>
    <%= f.label :professor %><br />
    <%= f.check_box :professor %>
  </div>

  <div>
    <%= f.submit "Update Profile" %>
  </div>

  <div>
  <h1>Details for <%= @user.email %></h1>
  <!-- Other user details here -->

  <%= link_to "Back to Home", root_path, class: "btn btn-primary" %>
</div>

<% end %>