config/routes.rb
Rails.application.routes.draw do
  # Routes for the Follow request resource:

  # CREATE
  post("/insert_follow_request", { :controller => "follow_requests", :action => "create" })
          
  # READ
  get("/follow_requests", { :controller => "follow_requests", :action => "index" })
  
  get("/follow_requests/:path_id", { :controller => "follow_requests", :action => "show" })
  
  # UPDATE
  
  post("/modify_follow_request/:path_id", { :controller => "follow_requests", :action => "update" })
  
  # DELETE
  get("/delete_follow_request/:path_id", { :controller => "follow_requests", :action => "destroy" })

  #------------------------------

  # Routes for the Post resource:

  # CREATE
  post("/insert_post", { :controller => "posts", :action => "create" })
          
  # READ
  get("/posts", { :controller => "posts", :action => "index" })
  
  get("/posts/:path_id", { :controller => "posts", :action => "show" })

  # Routes for Comments
post "/insert_comment", { controller: "comments", action: "create" }

# Routes for Likes
post "/insert_like", { controller: "likes", action: "create" }



  resources :posts do
    resources :comments, only: [:index, :create]
  end
  
  
  # UPDATE
  
  post("/modify_post/:path_id", { :controller => "posts", :action => "update" })
  
  # DELETE
  get("/delete_post/:path_id", { :controller => "posts", :action => "destroy" })

  #------------------------------

  # Routes for the Like resource:

  # CREATE
  post("/insert_like", { :controller => "likes", :action => "create" })
          
  # READ
  get("/likes", { :controller => "likes", :action => "index" })
  
  get("/likes/:path_id", { :controller => "likes", :action => "show" })
  
  # UPDATE
  
  post("/modify_like/:path_id", { :controller => "likes", :action => "update" })
  
  # DELETE
  get("/delete_like/:path_id", { :controller => "likes", :action => "destroy" })

  #------------------------------

  # Routes for the Comment resource:


  # CREATE
  post("/insert_comment", { :controller => "comments", :action => "create" })
          
  # READ
  get("/comments", { :controller => "comments", :action => "index" })
  
  get("/comments/:path_id", { :controller => "comments", :action => "show" })
  
  # UPDATE
  
  post("/modify_comment/:path_id", { :controller => "comments", :action => "update" })
  
  # DELETE
  get("/delete_comment/:path_id", { :controller => "comments", :action => "destroy" })

  #------------------------------

  # Routes for the Job application resource:

  # CREATE

  post("/insert_job_application", { :controller => "job_applications", :action => "create" })
          
  # READ
  get("/job_applications", { :controller => "job_applications", :action => "index" })
  
  get("/job_applications/:path_id", { :controller => "job_applications", :action => "show" })
  
  # UPDATE
  
  post("/modify_job_application/:path_id", { :controller => "job_applications", :action => "update" })
  
  # DELETE
  get("/delete_job_application/:path_id", { :controller => "job_applications", :action => "destroy" })

  #------------------------------

  # Routes for the Job posting resource:

  # CREATE

  post("/insert_job_posting", { :controller => "job_postings", :action => "create" })
          
  # READ
  get("/job_postings", { :controller => "job_postings", :action => "index" })
  
  resources :job_postings, only: [:index, :show]

  get("/job_postings/:path_id", { :controller => "job_postings", :action => "show" })
  

  # UPDATE
  
  post("/modify_job_posting/:path_id", { :controller => "job_postings", :action => "update" })
  
  # DELETE
  get("/delete_job_posting/:path_id", { :controller => "job_postings", :action => "destroy" })

  resources :job_postings do
    resources :job_applications, only: [:new, :create, :index]

  end
  

  #------------------------------

  devise_for :users

  get "/alumni_directory", { :controller => "users", :action => "directory" }
  get "/users/:user_id/posts", { :controller => "posts", :action => "user_posts" }
  root to: "pages#home"

  get "/profile/edit", to: "users#edit", as: "edit_profile"
  patch "/profile", to: "users#update", as: "update_profile"



  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"

  
end

app/models/job_posting.rb
# == Schema Information
#
# Table name: job_postings
#
#  id                     :bigint           not null, primary key
#  company                :string
#  compensation           :string
#  job_applications_count :integer
#  sector_of_occupation   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :integer
#
class JobPosting < ApplicationRecord

  belongs_to :user, required: true, class_name: "User", foreign_key: "user_id"
  has_many  :job_applications, class_name: "JobApplication", foreign_key: "job_posting_id", dependent: :destroy

  
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  def index
    matching_job_postings = JobPosting.all

    @list_of_job_postings = matching_job_postings.order({ :created_at => :desc })

    render({ :template => "job_postings/index" })
  end

  def show
    @the_job_posting = JobPosting.find(params[:id])
  end

def create
    the_job_posting = JobPosting.new
    the_job_posting.company = params.fetch("query_company")
    the_job_posting.sector_of_occupation = params.fetch("query_sector_of_occupation")
    the_job_posting.compensation = params.fetch("query_compensation")
    the_job_posting.user_id = current_user.id
    the_job_posting.job_applications_count = params.fetch("query_job_applications_count")

    if the_job_posting.valid?
      the_job_posting.save
      redirect_to("/job_postings", { notice: "Job posting created successfully." })
    else
      redirect_to("/job_postings", { alert: the_job_posting.errors.full_messages.to_sentence })
    end
  end


  def update
    the_id = params.fetch("path_id")
    the_job_posting = JobPosting.where({ :id => the_id }).at(0)

    the_job_posting.company = params.fetch("query_company")
    the_job_posting.sector_of_occupation = params.fetch("query_sector_of_occupation")
    the_job_posting.compensation = params.fetch("query_compensation")
    the_job_posting.user_id = params.fetch("query_user_id")
    the_job_posting.job_applications_count = params.fetch("query_job_applications_count")

    if the_job_posting.valid?
      the_job_posting.save
      redirect_to("/job_postings/#{the_job_posting.id}", { :notice => "Job posting updated successfully."} )
    else
      redirect_to("/job_postings/#{the_job_posting.id}", { :alert => the_job_posting.errors.full_messages.to_sentence })
    end
  end

  def destroy
    the_id = params.fetch("path_id")
    the_job_posting = JobPosting.where({ :id => the_id }).at(0)

    the_job_posting.destroy

    redirect_to("/job_postings", { :notice => "Job posting deleted successfully."} )
  end
end

app/views/job_postings/index.html.erb
<div>
  <div>
    <h1>
      List of all job postings
    </h1>
  </div>
</div>

<hr>

<div>
  <div>
    <h2>
      Add a new job posting
    </h2>

    <form action="/insert_job_posting" method="post">
      <div>
        <label for="company_box">
          Company
        </label>

        <input type="text" id="company_box" name="query_company">
      </div>

      <div>
        <label for="sector_of_occupation_box">
          Sector of occupation
        </label>

        <input type="text" id="sector_of_occupation_box" name="query_sector_of_occupation">
      </div>

      <div>
        <label for="compensation_box">
          Compensation
        </label>

        <input type="text" id="compensation_box" name="query_compensation">
      </div>

 
      <div>
        <label for="job_applications_count_box">
          Job applications count
        </label>

        <input type="text" id="job_applications_count_box" name="query_job_applications_count">
      </div>

      <button>
        Create job posting
      </button>
    </form>
  </div>
</div>

<hr>
<div>
  <div>
    <table border="1">
      <tr>
        <th>
          ID
        </th>

        <th>
          Company
        </th>

        <th>
          Sector of occupation
        </th>

        <th>
          Compensation
        </th>

        <th>
          User
        </th>

        <th>
          Job applications count
        </th>

        <th>
          Created at
        </th>

        <th>
          Updated at
        </th>

        <th>
        </th>
      </tr>

      <% @list_of_job_postings.each do |a_job_posting| %>
      <tr>
        <td>
          <%= a_job_posting.id %>
        </td>

        <td>
          <%= a_job_posting.company %>
        </td>

        <td>
          <%= a_job_posting.sector_of_occupation %>
        </td>

        <td>
          <%= a_job_posting.compensation %>
        </td>

        <td>
          <%= a_job_posting.user_id %>
        </td>

        <td>
          <%= a_job_posting.job_applications_count %>
        </td>

        <td>
          <%= time_ago_in_words(a_job_posting.created_at) %> ago
        </td>
        <td>
          <%= time_ago_in_words(a_job_posting.updated_at) %> ago
        </td>

        <td>
          <a href="/job_postings/<%= a_job_posting.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<hr>

app/views/job_postings/show.html.erb
<div>
  <div>
    <h1>
      Job posting #<%= @the_job_posting.id %> details
    </h1>

    <div>
      <div>
        <a href="/job_postings">
          Go back
        </a>
      </div>

      <div>
        <a href="/delete_job_posting/<%= @the_job_posting.id %>">
          Delete job posting
        </a>
      </div>
    </div>

    <dl>
      <dt>
        Company
      </dt>
      <dd>
        <%= @the_job_posting.company %>
      </dd>

      <dt>
        Sector of occupation
      </dt>
      <dd>
        <%= @the_job_posting.sector_of_occupation %>
      </dd>

      <dt>
        Compensation
      </dt>
      <dd>
        <%= @the_job_posting.compensation %>
      </dd>

      <dt>
        User
      </dt>
      <dd>
        <%= @the_job_posting.user_id %>
      </dd>

      <dt>
        Job applications count
      </dt>
      <dd>
        <%= @the_job_posting.job_applications_count %>
      </dd>

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_job_posting.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_job_posting.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>

<hr>


<div>
  <div>
    <h2>
      Edit job posting
    </h2>

    <form action="/modify_job_posting/<%= @the_job_posting.id %>"  method="post" >
      <div>
        <label for="company_box">
          Company
        </label>

        <input type="text" id="company_box" name="query_company" value="<%= @the_job_posting.company %>">
      </div>

      <div>
        <label for="sector_of_occupation_box">
          Sector of occupation
        </label>

        <input type="text" id="sector_of_occupation_box" name="query_sector_of_occupation" value="<%= @the_job_posting.sector_of_occupation %>">
      </div>

      <div>
        <label for="compensation_box">
          Compensation
        </label>

        <input type="text" id="compensation_box" name="query_compensation" value="<%= @the_job_posting.compensation %>">
      </div>

      <div>
        <label for="user_id_box">
          User
        </label>

        <input type="text" id="user_id_box" name="query_user_id" value="<%= @the_job_posting.user_id %>">
      </div>

      <div>
        <label for="job_applications_count_box">
          Job applications count
        </label>

        <input type="text" id="job_applications_count_box" name="query_job_applications_count" value="<%= @the_job_posting.job_applications_count %>">
      </div>

      <button>
        Update job posting
      </button>
    </form>
  </div>
</div>

<h2>Applications</h2>
<% if @job_posting.present? %>
  <%= link_to "Apply for this job", new_job_posting_job_application_path(@job_posting), class: "btn btn-primary" %>
<% else %>
  <p>Job posting not found.</p>
<% end %>

<hr>