config/routes.rb
Rails.application.routes.draw do
  # Routes for the Follow request resource:

  # CREATE
  post("/insert_follow_request", { :controller => "follow_requests", :action => "create" })
          
  # READ
  get("/follow_requests", { :controller => "follow_requests", :action => "index" })
  
  get("/follow_requests/:path_id", { :controller => "follow_requests", :action => "show" })
  
  # UPDATE
  
  post("/modify_follow_request/:path_id", { :controller => "follow_requests", :action => "update" })
  
  # DELETE
  get("/delete_follow_request/:path_id", { :controller => "follow_requests", :action => "destroy" })

  #------------------------------

  # Routes for the Post resource:

  # CREATE
  post("/insert_post", { :controller => "posts", :action => "create" })
          
  # READ
  get("/posts", { :controller => "posts", :action => "index" })
  
  get("/posts/:path_id", { :controller => "posts", :action => "show" })

  # Routes for Comments
post "/insert_comment", { controller: "comments", action: "create" }

# Routes for Likes
post "/insert_like", { controller: "likes", action: "create" }



  resources :posts do
    resources :comments, only: [:index, :create]
  end
  
  
  # UPDATE
  
  post("/modify_post/:path_id", { :controller => "posts", :action => "update" })
  
  # DELETE
  get("/delete_post/:path_id", { :controller => "posts", :action => "destroy" })

  #------------------------------

  # Routes for the Like resource:

  # CREATE
  post("/insert_like", { :controller => "likes", :action => "create" })
          
  # READ
  get("/likes", { :controller => "likes", :action => "index" })
  
  get("/likes/:path_id", { :controller => "likes", :action => "show" })
  
  # UPDATE
  
  post("/modify_like/:path_id", { :controller => "likes", :action => "update" })
  
  # DELETE
  get("/delete_like/:path_id", { :controller => "likes", :action => "destroy" })

  #------------------------------

  # Routes for the Comment resource:


  # CREATE
  post("/insert_comment", { :controller => "comments", :action => "create" })
          
  # READ
  get("/comments", { :controller => "comments", :action => "index" })
  
  get("/comments/:path_id", { :controller => "comments", :action => "show" })
  
  # UPDATE
  
  post("/modify_comment/:path_id", { :controller => "comments", :action => "update" })
  
  # DELETE
  get("/delete_comment/:path_id", { :controller => "comments", :action => "destroy" })

  #------------------------------

  # Routes for the Job application resource:

  # CREATE

  post("/insert_job_application", { :controller => "job_applications", :action => "create" })
          
  # READ
  get("/job_applications", { :controller => "job_applications", :action => "index" })
  
  get("/job_applications/:path_id", { :controller => "job_applications", :action => "show" })
  
  # UPDATE
  
  post("/modify_job_application/:path_id", { :controller => "job_applications", :action => "update" })
  
  # DELETE
  get("/delete_job_application/:path_id", { :controller => "job_applications", :action => "destroy" })

  #------------------------------

  # Routes for the Job posting resource:

  # CREATE

  post("/insert_job_posting", { :controller => "job_postings", :action => "create" })
          
  # READ
  get("/job_postings", { :controller => "job_postings", :action => "index" })
  
  resources :job_postings, only: [:index, :show]

  get("/job_postings/:path_id", { :controller => "job_postings", :action => "show" })
  

  # UPDATE
  
  post("/modify_job_posting/:path_id", { :controller => "job_postings", :action => "update" })
  
  # DELETE
  get("/delete_job_posting/:path_id", { :controller => "job_postings", :action => "destroy" })

  resources :job_postings do
    resources :job_applications, only: [:new, :create, :index]

  end
  

  #------------------------------

  devise_for :users

  get "/alumni_directory", { :controller => "users", :action => "directory" }
  get "/users/:user_id/posts", { :controller => "posts", :action => "user_posts" }
  root to: "pages#home"

  get "/profile/edit", to: "users#edit", as: "edit_profile"
  patch "/profile", to: "users#update", as: "update_profile"



  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"

  
end

app/views/layouts/application.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UChicago Alumni Platform</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f8f9fa;
    }
    .uchicago-logo {
      max-width: 150px;
      margin: 20px auto;
      display: block;
    }
    .navbar {
      background-color: #800000;
      padding: 10px 20px;
    }
    .navbar a {
      color: white !important;
      text-decoration: none;
      margin-right: 15px;
      font-weight: bold;
    }
    .navbar a:hover {
      text-decoration: underline;
    }
    .btn {
      color: white;
      border: none;
    }
    .btn-primary {
      background-color: #800000;
    }
    .btn-secondary {
      background-color: #b3b3b3;
    }
    .btn-info {
      background-color: #0056b3;
    }
    .btn-success {
      background-color: #198754;
    }
    .btn-warning {
      background-color: #ffc107;
    }
    .btn-tough {
      background-color: #6c757d;
    }
    hr {
      border: 1px solid #800000;
    }
    .footer {
      text-align: center;
      padding: 10px 0;
      background-color: #f8f9fa;
      margin-top: 20px;
    }
  </style>
</head>


<body>
  <!-- Header with Logo -->
  <header>
    <%= image_tag "https://chen.uchicago.edu/files/2019/07/UChicago-logo-1024x1024.jpg", alt: "University of Chicago", class: "uchicago-logo" %>
  </header>

  <!-- Navigation Bar -->
  <nav class="navbar">
    <a href="<%= root_path %>">Home</a>
    <a href="<%= alumni_directory_path %>">Alumni Directory</a>
    <a href="<%= job_postings_path %>">Job Postings</a>
    <a href="<%= job_applications_path %>">Job Applications</a>
    <a href="<%= posts_path %>">Posts</a>
    <a href="<%= edit_user_registration_path %>">Edit Profile</a>
    <a href="<%= follow_requests_path %>">Follow Requests</a>
  </nav>

  <hr>

  <!-- Main Content -->
  <div class="container mt-4">
    <%= yield %>
  </div>

  <!-- Footer -->
  <footer class="footer">
    <p>&copy; <%= Time.current.year %> University of Chicago Alumni Platform. All rights reserved.</p>
  </footer>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.4.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>